//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBuy.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTestEntities : DbContext
    {
        public DBTestEntities()
            : base("name=DBTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<TaskStatuses> TaskStatuses { get; set; }
        public virtual DbSet<EpisodeLocations> EpisodeLocations { get; set; }
        public virtual DbSet<Episodes> Episodes { get; set; }
        public virtual DbSet<ItemComponents> ItemComponents { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<LocationItems> LocationItems { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<OurThings> OurThings { get; set; }
        public virtual DbSet<OurThingsItems> OurThingsItems { get; set; }
        public virtual DbSet<Workshop> Workshop { get; set; }
        public virtual DbSet<WorkshopItems> WorkshopItems { get; set; }
        public virtual DbSet<TaskDayOfWeek> TaskDayOfWeek { get; set; }
    }
}
