//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBuy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDayOfWeek
    {
        public int Id { get; set; }
        public int TaskID { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<System.DateTime> DoneDate { get; set; }
        public bool Done { get; set; }
        public string Description { get; set; }
    
        public virtual Tasks Tasks { get; set; }
    }
}
